on:
  workflow_dispatch:

jobs:
  scans:
    runs-on: ubuntu-latest
    name: Sparse commit
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}
          sparse-checkout: urls.txt

      - run: touch results/$RANDOM.txt

      - uses: EndBug/add-and-commit@v9
        with:
          add: "--sparse results"
          pull: "--rebase --autostash ..."
          default_author: "github_actions"
          message: "commit"
